bcgov/sso-realm-registry

app/pages/my-dashboard.tsx

move the window to the top whenever the "edit" button been clicked

feat: rightHandPanel

---

.tool-versions
app/controllers/realm.ts
app/page-partials/my-dashboard/RealmEdit.tsx
app/page-partials/my-dashboard/RealmTable.tsx
app/pages/api/realms/one.ts
app/types/realm-profile.ts
helm/webapp/migration.sql

- add postgres 11.4 in .tool-versions
- add the second technical contact attribute (idir and email);
- for current permission level, the sec_tech_contact can be changed by any admin/po/technic owner account;

feat: secTechContact

---

app/page-partials/my-dashboard/RealmEdit.tsx
app/pages/api/realms/one.ts
app/types/realm-profile.ts

- fix display typo
- fix the edit & save for PO account
- add more info to product_owner info hover

chore: fixTypoAndBug

---

app/page-partials/my-dashboard/RealmEdit.tsx
app/styles/globals.css

ticket# 1206
- changed hover info content
- add mailto button

chore: add mailto button

---

helm/webapp/templates/deployment.yaml
helm/webapp/values-c6af30-dev.yaml
helm/webapp/values-c6af30-prod.yaml

Fixes [SSOTEAM-1095](https://bcdevex.atlassian.net/browse/SSOTEAM-1095)

feat: pass github environment variables from vault

---

app/yarn.lock

fix: lockfile

---

app/page-partials/my-dashboard/RealmEdit.tsx
app/page-partials/my-dashboard/RealmTable.tsx
app/pages/custom-realm-form.tsx
app/types/realm-profile.ts

Fix some issues in build process, update types to have new camelCase keys, some linting errors.

fix: build

---

app/utils/mailer.ts

change case in email func to camel

fix: email

---

app/__tests__/custom-realm-dashboard.test.tsx
app/page-partials/custom-realm-dashboard/CustomRealmTabs.tsx
app/pages/custom-realm-form.tsx
app/services/events.ts
app/types/event.ts

add tab for events, fix bug in form for other details

feat: add events

---

app/__tests__/custom-realm-form.test.tsx
app/components/RealmForm.tsx
app/page-partials/my-dashboard/RealmEdit.tsx
app/validators/create-realm.ts

Adding some feedback from review:
- Updated some validations, made product name required, optional fields nullable
- Put in a confirmation modal for editing view, scroll error into view if form invalid
- Removed some unused code, updated branch/division types

chore: form updates

---

app/components/RealmForm.tsx
app/types/realm-profile.ts

Make sure only one other user is added to users array, set that to the default form data when updating

fix: others

---

app/utils/mailer.ts

Update email content for realm approval/declining

chore: update emails

---

app/page-partials/my-dashboard/RealmURIs.tsx
app/pages/api/realms/[id].ts
app/pages/api/realms/pending.ts
app/utils/helpers.ts
app/utils/mailer.ts

Fixes [SSOTEAM-1221](https://bcdevex.atlassian.net/browse/SSOTEAM-1221)

feat: ready to use email after terraform applies the realm and improved consistency for emails

---

app/pages/custom-realm-dashboard.tsx

Include archived requests, add filter for that column

chore: show archived requests in the admin dashboard

---

app/utils/mailer.ts

chore: cc email

---

app/layout/Layout.tsx
app/pages/index.tsx
app/utils/helpers.ts
app/utils/mailer.ts

chore: links

---

app/layout/Layout.tsx
app/package.json
app/yarn.lock

logout idle users. Just made two small changes to checkSession, the date was in milliseconds so always bigger than the expiry time in the token, which was making a callout to getSession every second instead of only when token was expired. Called the update method on session otherwise it was staying stale in the component context

feat: logout idle

---

app/components/Modal.tsx
app/context/modal.ts
app/layout/Layout.tsx

Logout user if they dismiss the session expiring modal

chore: logout modal

---

app/context/modal.ts

fix: typescript

---

app/__tests__/realm-edit.test.tsx
app/pages/realm/[rid].tsx

allow admins to always see the edit page

fix: admin edit rights

---

app/components/RealmForm.tsx
app/pages/custom-realm-form.tsx
app/pages/index.tsx
app/styles/globals.css

Some typography updates, and switched out the link while changing the underline.

chore: typography styles

---

app/__tests__/api/delete-realm.test.ts
app/__tests__/api/restore-realm.test.ts
app/__tests__/api/update-realm.test.ts
app/utils/mailer.ts

include secondary tech contact in emails

chore: include secondary tech contact

---

app/__tests__/api/delete-realm.test.ts
app/__tests__/api/restore-realm.test.ts
app/__tests__/api/update-realm.test.ts
app/utils/mailer.ts

chore: release

---

app/controllers/keycloak.ts

remove manage account role when creating custom realms

chore: remove manage-acct
